# Generated by Django 4.2.22 on 2025-08-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia_api', '0002_personaje_alter_profiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='personajes/'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
